In [1]:
import pandas as pd
import numpy as np

In [2]:
clicks = pd.read_csv("clicks.csv")

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (16,17) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
clicks.head()

,advertiser_id,action_id,source_id,created,country_code,latitude,longitude,wifi_connection,carrier_id,trans_id,os_minor,agent_device,os_major,specs_brand,brand,timeToClick,touchX,touchY,ref_type,ref_hash
0,1,NaN,2,2019-04-18T05:27:42.197Z,6287817205707153877,1.714547,0.871535,False,3.0,9JMAfrb-b9cSEVCJb0P9JfihGthaS7E,1.517644e+18,NaN,5.131616e+18,71913840936116953,0.0,2.317,0.968,0.503,1891515180541284343,1293710398598742392
1,1,NaN,1,2019-04-18T05:27:03.164Z,6287817205707153877,1.714512,0.871062,True,2.0,r3xtTRv2lInfiXG8JI3NQsNcBo8GyFQ,1.288578e+18,NaN,3.908390e+18,3576558787748411622,1.0,7.653,0.712,1.689,1891515180541284343,1663930990551616564
2,1,NaN,1,2019-04-18T05:42:07.926Z,6287817205707153877,1.714547,0.871535,True,4.0,WOnHFqQtY48z_ygKZ-030U_g0TMGVMw,2.238736e+18,NaN,3.581233e+18,3576558787748411622,NaN,464.796,0.227,0.251,1891515180541284343,8488038938665586188
3,1,NaN,1,2019-04-18T05:26:04.446Z,6287817205707153877,1.708041,0.870772,True,1.0,wQMLLmYqiFhSuha9p9B13PMtcyBW_vM,2.411640e+18,NaN,3.908390e+18,3576558787748411622,NaN,225.311,0.696,6.587,1891515180541284343,6488361690105189959
4,1,NaN,1,2019-04-18T05:23:37.764Z,6287817205707153877,1.715514,0.870772,True,2.0,GeFoyBzMA7taylMxxjzlNPTU-n4FXFs,1.517644e+18,NaN,5.131616e+18,3576558787748411622,0.0,84.736,0.059,0.142,1891515180541284343,1348993302102753419

In [4]:
installs = pd.read_csv("installs.csv")

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3044: DtypeWarning: Columns (4,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [8]:
brand_clicks = clicks.groupby("ref_hash").agg({"specs_brand":"mean"})

In [9]:
installs["cantidad"] = 1

In [10]:
installs_cant = installs.groupby("ref_hash").agg({"cantidad":"sum"})

In [16]:
a = installs_cant.merge(brand_clicks, right_index=True, left_index=True, how="left")

In [34]:
installs[installs["ref_hash"] == 9223189551280812934]

,created,application_id,ref_type,ref_hash,click_hash,attributed,implicit,device_countrycode,device_brand,device_model,session_user_agent,user_agent,event_uuid,kind,wifi,trans_id,ip_address,device_language,cantidad
314402,2019-04-18 19:02:43.916,133,1891515180541284343,9223189551280812934,NaN,False,False,6287817205707153877,2.523246e+18,2.827096e+17,http-kit/2.0,Dalvik/2.1.0 (Linux; U; Android 7.1.1; LG-M700...,NaN,NaN,True,NaN,1344911218907331780,6.977049e+18,1
314405,2019-04-18 19:02:18.331,133,1891515180541284343,9223189551280812934,NaN,False,True,6287817205707153877,2.523246e+18,2.827096e+17,http-kit/2.0,Dalvik/2.1.0 (Linux; U; Android 7.1.1; LG-M700...,709e4390-f628-4402-9ea4-fc09aff2f91e,af_app_opened,True,NaN,1344911218907331780,6.977049e+18,1

In [37]:
installs.click_hash.value_counts()

nQS5r_E9rU9lbkofA2mJM1HKGnnWabk    1
nN0N9gcX3EIf9jLjFRyUnFhkxf4X81E    1
bQ0wAx9phyRCGN3Hq6k_v6YFrXVmZs8    1
KJZhcLdakupq_wz5ClIXqaalotQfPHE    1
n4ICrt3bSWMJvSGD1w3iOXdMfLcEOXw    1
8MgarrL6sSp8n9bXCpdabpe1t0kUuJM    1
Niz9fHZoHLCFEpTsN3lG5hVSktmMAkw    1
yB65dsjgdzaXWupYQ8Utn6RLOQyxP4o    1
fpPoskE8-IG-ll3a6n-kjf7XNN-bU70    1
dUQUg1WlJfLeZ3HTkozUMspTODYyKFQ    1
6zOpAOzuemRFgj84YAYYKiMHuD6VN_g    1
9izjSeZVIwV0nm83GS-2nYokputUELQ    1
w8hwdMqXF2ecRc80XBRjiLXwm9wgJp0    1
iYsEJTBJKjfIEiDVkhV5KOfH068Jw80    1
T14VtzQvlg55PVnoCmDxrUdVQ1MxS1w    1
vRxz2JGVUXO37zAgFVNHPHelcMBT054    1
U-piolGE3apqB6BqHKOIE6KOEbK9R-g    1
yBOP2MYl_1xu4aZWdJ5bFzn02o5Ct5Q    1
1-O1rZTesmd3SGiClmq9lJcC5WjJtcw    1
bp-S6shuoyGAk3lzVvkOf9JSkmy9qtQ    1
PSzoKbS_IWERdunCHBbrYXGcHJox18k    1
pY1AZ_j6BonFlBHd64XY7Z5XQVaJ6dQ    1
W29Q_7VqqGV40GZzrmavj10S81PySrg    1
1nXTeEORZRpJAgrzL51tXvEkoE5cQTM    1
NK6wqJaE7hg5ZiqIAIN1uzEZJoo-Ce4    1
pT_50ttbEh4zyZ8Po08VzZzmtbF46uQ    1
HW9z3UlpYeUdFTAu_2kE6zjabWl6V4M    1
Mh1Yu09m8Zib-Vkl3xdNFsp2pjHZM9c    1
cZYNjCe90gjnxEWGmKS_57TSNqPMu5A    1
AnhIDGxT013h1mPDnA50VyFge4P-7tM    1
                                  ..
7u-pHwmznQzIb8GY1pa9HBOE_GYHqDs    1
80vL1wMj5WstCXjRcYRgD-3e80uP6ZA    1
H2_8WD5RpTqJGVLejq2ZMPkV9AlMw2g    1
bPEb6RVaWZH3Pqqo8jqZ7MKbV2GdED0    1
nAfFxHCdjw6eOAxheazSumC84VDyBeY    1
iugjLtEdyGPvrD0pDGvLtAnUX0N6keQ    1
v6cuD57YUx4T4miLUND2mt3TIVBjCT4    1
3DezKJSuiiTtvXBxddmgIdQrqakNqMY    1
ZsGLgDqrsr-HvsbgMqPr6LqtH-lMt1E    1
DX7tWLQWRJovn-UNf2O_JMb5s-nFfWU    1
AmePvqQ0vOZEQFosw-E7SdPYuV6QP2Q    1
esVU-K9sd-ssQ8Q6QNM_TVn-LZqxRiw    1
L0SpNPbP3alOShn4kHKYSz44NUonV90    1
L9-9Qw9C3L1IJ16eGyGLzi30BEYZbIw    1
MN7a7aC5qewqnOZDTAyZKOluCovm4WQ    1
l2w5xYAvyW2JZmKXle-bgwbHr1j7f68    1
WgTKfEH-WfXpPMuPBsTKw6AZ0saMgiU    1
eoKjdaYulVHXm6mQ9JcrgGU76m1E-iY    1
FNDOk87G7m3hjwluhtBcI_MkAqBSnUo    1
pYpcyDRc_26turmj_LLLeIIaNpNMnBo    1
x8nHasy52NPDzBT8eWkDkdA0aaiODpM    1
YaG7i-Pe02tRH65K9fON2uyD5jg0aZ0    1
4DWw2TdZ_3RLqZmEjX_OJT6naVsaIEY    1
9EbCyY4_Q-3Xfn8j8l4I0x7PGImRnzY    1
Pq7GR_Ra9u0mXYw2wrOh5aVcNB7M4Dg    1
pORi7mHDI3RjoCAX03BCxJrr2iN1hGc    1
0Nc06MaitZbVd9ywiuBmyEKyi2NWGyc    1
7uZHQYWDCDa9gOnk_8YkeU9e8LlxCWA    1
M2CJAQooTBzWasrNi1Damv3V8AGbbb0    1
ge4lBt3DOgIg7YYWIYhhqmdqK9nWs6s    1
Name: click_hash, Length: 1142, dtype: int64

                     cantidad   specs_brand
ref_hash
40621409780134              1           NaN
41863526108385              4           NaN
90072729247980              1           NaN
135153013040192             1           NaN
161514654074162             1           NaN
168103949904656             1           NaN
186034136943920             1           NaN
283297668933729             1           NaN
342614246084071             1           NaN
345999128501141             1           NaN
347785260789835             1           NaN
365882020742330             1           NaN
416301579449694             1           NaN
420449720220692             1           NaN
448610188195811             2           NaN
456015810461357             1           NaN
457867161681660             1           NaN
468235013311868             1           NaN
475635010681369             2           NaN
519199987760489             1           NaN
530786270564316             1           NaN
538200907470757             1           NaN
558877640599287             1           NaN
622102439689666             3           NaN
642751118419841             1           NaN
655267966876774             1           NaN
717556230663455             1           NaN
719819620272773             1           NaN
732881181016646             1           NaN
759186287310366             1           NaN
...                       ...           ...
9222439452676054246         1           NaN
9222445878176178987         1           NaN
9222505600439168461         1           NaN
9222517399250029400         1           NaN
9222605308741024421         2           NaN
9222608508750105493         1           NaN
9222775201174486974         1           NaN
9222809061253378785         1           NaN
9222820903899321555         2           NaN
9222828776091827087         3           NaN
9222848912066710170         1           NaN
9222856470568969120         1           NaN
9222861184027496933         1           NaN
9222891164638072546         1           NaN
9222941581432951568         1           NaN
9222957264925735246         4           NaN
9223065111245755115         1           NaN
9223066346652706056         1           NaN
9223135580643723279         1           NaN
9223180934071401185         1           NaN
9223189551280812934         2  7.191384e+16
9223229584859890420         1  3.576559e+18
9223231006535555583         1           NaN
9223250784891904112         1           NaN
9223252295312976945         2           NaN
9223291601074715510         1           NaN
9223314893254762361         1           NaN
9223332684447638624         1           NaN
9223336706138545892         1           NaN
9223365873867066370         1           NaN

[393565 rows x 2 columns]